config/routes.rb
NerdBrigade::Application.routes.draw do

  resources :newsfeeds

  root to: 'newsfeeds#index'
  
  match ':main/:sub' => "newsfeeds#index", :as => :feed

  mount Monologue::Engine, :at => '/blog' # or whatever path, be it "/blog" or "/monologue"

end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base

  FEEDS = {
    :news => {
      :home => "http://blog.nola.com/news_impact/atom.xml",
      :crime => "http://blog.nola.com/crime_impact/atom.xml",
      :politics => "http://blog.nola.com/politics/atom.xml",
      :education => 'http://blog.nola.com/education_impact/atom.xml',
      :traffic => 'http://blog.nola.com/traffic/atom.xml',
      :opinions => "http://blog.nola.com/opinions_impact/atom.xml"
    },
    :business => {
      :home => "http://blog.nola.com/business_impact/atom.xml",
      :hollywood_south => "http://topics.nola.com/tag/hollywood-south/atom.xml",
      :science_and_technology => "http://impact.nola.com/science/atom.xml",
      :real_estate => 'http://impact.nola.com/realestatetransfers/atom.xml',
      :corporate_earnings => "http://topics.nola.com/tag/corporate-earnings/atom.xml"
    },
    :sports => {
      :home => "http://blog.nola.com/sports_impact/atom.xml",
      :saints => "http://blog.nola.com/saints_impact/atom.xml",
      :hornets => "http://blog.nola.com/hornets_impact/atom.xml",
      :lsu => "http://blog.nola.com/lsu_impact/atom.xml",
      :tulane => "http://blog.nola.com/tulane_impact/atom.xml"
    }
  
  }
  
  def self.headers
    FEEDS.collect{|x,k| x.to_s}
  end
  
  def self.subheaders(main)
    FEEDS[main.to_sym].collect{|x,k| x.to_s}
  end
  
  def self.get_feed(main, sub)
    FEEDS[main.to_sym][sub.to_sym]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/newsfeeds_controller.rb
class NewsfeedsController < ApplicationController

  def index
    params[:main] ||= 'news'
    params[:sub] ||= 'home'

    @news = Feedzirra::Feed.fetch_and_parse(Newsfeed.get_feed(params[:main], params[:sub]))
    @title = @news.description.present? ? @news.description.titlecase : "AwesomeNola.com"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cc_html(options={}, &blk)
    attrs = options.map { |(k, v)| " #{h k}='#{h v}'" }.join('')
    [ "<!--[if lt IE 7]> <html#{attrs} class='no-js lt-ie9 lt-ie8 lt-ie7'> <![endif]-->",
      "<!--[if IE 7]>    <html#{attrs} class='no-js lt-ie9 lt-ie8'> <![endif]-->",
      "<!--[if IE 8]>    <html#{attrs} class='no-js lt-ie9'> <![endif]-->",
      "<!--[if gt IE 8]><!--> <html#{attrs} class='no-js'> <!--<![endif]-->",
      capture_haml(&blk).strip,
      "</html>"
    ].join("\n").html_safe
  end
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/views/layouts/_original_bootstrap_html5.html.haml
/Main hero unit for a primary marketing message or call to action
.hero-unit
  %h1
    Hello, world!
  %p
    This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
  %p
    %a.btn.btn-primary.btn-large
      Learn more &raquo;
/.hero-unit

/Example row of columns
.row
  .span4
    %h2
      Heading
    %p
      Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      =link_to "View Details &raquo;", "#", :class => "btn"
  .span4
    %h2
      Heading
    %p
      Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      =link_to "View Details &raquo;", "#", :class => "btn"
  .span4
    %h2
      Heading
    %p
      Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      =link_to "View Details &raquo;", "#", :class => "btn"
/.row


.row
  .span4
    %h2
      Heading
    %p
      Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      =link_to "View Details &raquo;", "#", :class => "btn"
  .span4
    %h2
      Heading
    %p
      Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      =link_to "View Details &raquo;", "#", :class => "btn"
  .span4
    %h2
      Heading
    %p
      Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      =link_to "View Details &raquo;", "#", :class => "btn"
/.row

app/views/layouts/application.html.haml
!!! 5
!= cc_html(:lang => 'en') do
  %head
    %meta{'charset' => "utf-8"}
    %meta{'http-equiv' => "X-UA-Compatible", 'content' => "IE=edge,chrome=1"}

    %title=@title || "NOLA(DOT)COM re-envisioned"
    %meta{'name' => "description", 'content' => "A re-envisioning of what the nola.com page could look like"}
    %meta{'name' => "author", 'content' => "daybreaker"}

    %meta{'name' => "viewport", 'content' => "width=device-width"}

    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
	  
    :css
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
	  
    = csrf_meta_tags  
  %body
    /[if lt IE 7]
      %p.chromeframe
        Your browser is
        %em="ancient!"
        =link_to "Upgrade to a different browser", "http://browsehappy.com/"
        or</a> or <a href=
        =link_to "install Google Chrome Frame", "http://www.google.com/chromeframe/?redirect=true"
        to experience this site

    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          =link_to "NOLA.com", root_path, :class => "brand"
          %ul.nav
            - Newsfeed.headers.each do |header|
              -active = params[:main] && params[:main] == header
              %li{:class => active ?  "active" : "dropdown"}
                - if !active               
                  %a{:class => "dropdown-toggle", :data => {:toggle => "dropdown"}, :href => "#"}
                    = header.titlecase
                    %b.caret
                  %ul.dropdown-menu
                    - Newsfeed.subheaders(header).each do |sub|
                      %li{:class => params[:sub] && params[:sub] == sub ? "active" : ""}
                        = link_to sub.titlecase, feed_url(:main => header, :sub => sub)
                - else 
                  %span.text=header.titlecase
          /.nav-collapse
        /.container
      /.navbar-inner
    /.navbar

    .container
      
      %header#overview.jumbotron.subhead
        .header-ad
          =image_tag "http://placehold.it/600x100&text=advertisement+space"
        .subnav
          %ul.nav.nav-pills
            - Newsfeed.subheaders(params[:main]).each do |sub|
              %li{:class => params[:sub] && params[:sub] == sub ? "active" : ""}
                = link_to sub.titlecase, feed_url(:main => params[:main], :sub => sub)
              -#%li.dropdown.active
              -#  %a{:class => "dropdown-toggle", :data => {:toggle => "dropdown"}, :href => "#"}
              -#    News
              -#    %b.caret
              -#  %ul.dropdown-menu
              -#    %li.active
              -#      =link_to "General", "/news-general"
              -#    %li
              -#      =link_to "World", "/world-news"

      
      = yield
      
      %hr

      %footer
        %p
          &copy; Brad Huber & Associates 2012
    
    /.container
 
  /<script>
  /  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  /  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  /  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  /  s.parentNode.insertBefore(g,s)}(document,'script'));
  /</script>

app/views/newsfeeds/index.html.haml
- @news.entries.each_slice(3) do |batch|
  .row
  - batch.entries.each do |entry|
    .span4{:style => 'width: 290px'}
      %h2
        =entry.title
      %p
        =entry.summary
      %p
        =link_to raw("Read More &raquo;") , entry.links.first, :class => "btn"
.clear
!= ap @news.entries.first